#!/usr/bin/env bash
# echo "entered aliases"

#################################################
############### Alias Definitions ###############
#################################################

if command -v bat &>/dev/null; then
    # Use bat instead of cat
    alias cat='bat'
fi

alias grep='grep --color=auto'
if command -v egrep &>/dev/null; then
    alias egrep='egrep --color=auto'
else
    alias egrep='grep -E --color=auto'
fi
if command -v fgrep &>/dev/null; then
    alias fgrep='fgrep --color=auto'
else
    alias fgrep='grep -F --color=auto'
fi
if command -v rgrep &>/dev/null; then
    alias rgrep='rgrep --color=auto'
else
    alias rgrep='grep -r --color=auto'
fi
if command -v howdoi &>/dev/null; then
    alias howdoi='howdoi --color'
fi
if command -v delta &>/dev/null; then
    # Use delta instead of diff, it makes CLI diffs more readable
    alias diff='delta'
else
    alias diff='diff --color'
fi

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cdwsc='cd ${WORKSTATION_DIR}'
alias cpwd='pwd | pbcopy'
alias dir='dir --color=auto'
alias el='eza --all --long --header --icons'
alias elt='eza --all --long --header --icons --sort=time'
alias fapt='${WORKSTATION_DIR}/bin/pkgsearch.sh'
alias frf='${WORKSTATION_DIR}/bin/rfv.sh'
alias gss="git status"
alias gsu="git status -uno"
alias -- -='cd -'

# Check if 'less' is aliased; if not, assign it
if ! type less 2>/dev/null | grep -q "alias"; then
    alias less='less ${LESS:-}'
fi

# list aliases
if command -v eza &>/dev/null; then
    alias ls="eza"
    alias l="eza --oneline --classify"
    # ll - lists everything with directories first
    alias ll="eza --long --all --group-directories-first"
    # ld - lists only directories (no files)
    alias ld="eza --long --only-dirs"
    # lf - lists only files (no directories)
    alias lf="eza --long --classify | grep --invert-match /"
    # lh - lists only hidden files and directories
    alias lh="eza --long --all --group-directories-first .*"
    # lt - lists everything sorted by time modified
    alias lt="eza -al --sort=modified"
    alias ltr="eza -al --sort=modified --reverse"
    # export FZF_CTRL_T_COMMAND="eza --all --sort=type --oneline --color=always --icons"
    # export FZF_ALT_C_COMMAND="eza --all --all --only-dirs --oneline --color=always --icons"
else
    alias ls='ls --color=auto'
    alias l='ls -CF'
    alias la='ls -A'
    alias ll='ls -lAF'
    alias lt='ls -lAF --sort=time'
    alias ltr='ls -lAF --sort=time --reverse'
    # export FZF_CTRL_T_COMMAND="lt"
    # export FZF_ALT_C_COMMAND="ll \./*/"
fi
alias menu='${WORKSTATION_DIR}/bin/fzfmenu.sh'
alias nalalistup='sudo nala list --upgradable'
alias nalaupall="sudo nala upgrade \
--fix-broken \
--full \
--install-recommends \
--install-suggests \
--update"
alias numchars="wc --chars"
alias numlines="wc --lines"
alias numwords="wc --words"
alias open="xdg-open"
alias pbcopy="xsel --clipboard --input"
alias pbpaste="xsel --clipboard --output"
alias rm='echo "rm is disabled, use trash or /bin/rm instead."'
alias untar='tar -xzf'
alias vdir='vdir --color=auto'
alias watchdir='watch -n 1 --color tree --prune -C'

# browse any shell history file following the standard patterns:
alias allhist='find "${HOME}" \( -path '\''*zsh_history'\'' -o -path '\''*bash_history'\'' -o -path '\''*.history'\'' \) -a -type f | fzfp'
alias bathelp='bat --language=help'
alias wscfg='code ${WORKSTATION_DIR}/workstation_config.code-workspace'

# Shell-specific aliases
if [[ "${SHELL}" == *"bash"* && -n "${BASH_VERSION}" ]]; then
    src() {
        local bash_sources=(
            "${CONFIG_DIR}/bash/.bash_profile"
            "${CONFIG_DIR}/bash/.bashrc"
        )
        for bash_source in "${bash_sources[@]}"; do
            if [[ -f "${bash_source}" ]]; then
                source "${bash_source}"
            else
                echo "File not found: ${bash_source}"
            fi
        done
    }
elif [[ "${SHELL}" == *"zsh"* && -z "${BASH_VERSION}" ]]; then
    # src -> basically resets the shell and loads any modifications to the environment
    src() {
        env -i HOME="${HOME}"
        exec zsh
    }

    # These are handy, basically pretty-fies the output of -h, --help, and \?
    # Note: -h is not always a flag that shows help.
    alias -g -- -h='-h 2>&1 | bat --language=help --plain'
    alias -g -- --help='--help 2>&1 | bat --language=help --plain'
    alias -g -- \?='--help 2>&1 | bat --language=help --plain'
    alias history='history -t ${HIST_STAMPS}'

    alias -s html='google-chrome'
    alias -s py='python3'
fi
