'$schema' = "https://starship.rs/config-schema.json"

format = """
[](#1500ff)\
$username\
[](fg:#1500ff bg:#DA627D )\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#2ec122)\
$docker_context\
$conda\
$python\
[ ](fg:#2ec122)\
$fill\
$jobs\
[ ](fg:#bc57eb)\
$time\
$battery\
[ ](fg:#bc57eb)\
$line_break\
[⋙  ](fg:#0094ff)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = '[~~> ](fg:#d950ff)'

right_format = """
[](fg:#bc57eb)\
$cmd_duration\
$status\
[](fg:#bc57eb)\
"""

[line_break]
disabled = false

[character]
disabled = false
error_symbol = "[ ❌ ](fg:#ff0000)"
success_symbol = "[ ✅ ](fg:#00ff2d)"

[fill]
disabled = false
symbol = "-"

[battery]
disabled = false
full_symbol = " 🔋 "
charging_symbol = " ⚡️ "
discharging_symbol = " ⇣ "

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'blink red'
discharging_symbol = ' 💀 '

[[battery.display]]
threshold = 30
style = 'bold yellow' # when capacity is over 30%, the battery indicator will not be displayed

[[battery.display]]
threshold = 99
style = 'bold green'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = 'bold fg:#000000 bg:#bc57eb'
format = '[$time  ]($style)'

[cmd_duration]
style = 'fg:bold #000000 bg:#bc57eb'
format = "[  $duration ]($style)"
show_milliseconds = true
min_time = 500
show_notifications = true
min_time_to_notify = 300_000
notification_timeout = 5_000

[status]
disabled = false
style = "fg:bold #000000 bg:#bc57eb"
map_symbol = true
recognize_signal_code = true
pipestatus = true
symbol = '🔴 '
signal_symbol = "⚡ "
success_symbol = '🟢 SUCCESS'
sigint_symbol = "⛔ "
not_executable_symbol = "🚫 "
not_found_symbol = "🔍 "
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)'

[jobs]
symbol_threshold = 1
number_threshold = 1
format = "[ $symbol$number jobs ]($style)"

[username]
show_always = true
style_user = "fg:#FFFFFF bg:#1500ff"
style_root = "fg:#FFFFFF bg:#ff0000"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:bold #000000 bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Git status:
[git_branch]
symbol = ""
style = "fg:bold #000000 bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:bold #000000 bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

# Languages:
[c]
symbol = ""
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "🐹"
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:bold #000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

# Environment/Context:
[conda]
style = "fg:bold #000000 bg:#2ec122"
symbol = "🅒 "
ignore_base = false
format = '[$symbol$environment]($style)'

[docker_context]
symbol = "  "
style = "fg:bold #000000 bg:#2ec122"
format = '[ $symbol $context ]($style)'

[python]
version_format = "v${raw}"
style = "fg:bold #000000 bg:#2ec122"
symbol = ""
format = '[ [$symbol](fg:#bc57eb bg:#2ec122) ($version)]($style)'
