#!/usr/bin/zsh

export FZF_DEFAULT_OPTS="--height=60% \
--multi \
--cycle \
--hscroll-off=10 \
--filepath-word \
--layout=reverse \
--border \
--margin=1 \
--padding=1 \
--info=inline \
--marker='+' \
--ansi \
--tabstop=4 \
--preview-window 'border-bottom' \
--bind 'ctrl-/:change-preview-window(75%|50%|25%|hidden|)' \
--bind 'shift-up:preview-up' \
--bind 'shift-down:preview-down' \
--bind 'bspace:backward-delete-char/eof,ctrl-h:backward-delete-char/eof'"

export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree trash"
export FZF_COMPLETION_OPTS="${FZF_DEFAULT_OPTS} \
--border \
--info=inline \
--prompt=' FZF (comp)  '"

if command -v eza &>/dev/null; then
    export FZF_CTRL_T_COMMAND="eza \
    --all \
    --long \
    --oneline \
    --color=always \
    --icons=always \
    "
    export FZF_CTRL_T_OPTS=" \
    ${FZF_DEFAULT_OPTS} \
    --prompt=' FZF (ctlT)  ' \
    --preview='eza_bat_preview {}' \
    --bind='enter:execute:eza_icon_strip {}' \
    "

    export FZF_ALT_C_COMMAND="eza \
    --all \
    --only-dirs \
    --long \
    --oneline \
    --color=always \
    --icons=always \
    "
    export FZF_ALT_C_OPTS=" \
    --prompt=' FZF (altC)  ' \
    --preview='eza_bat_preview {}' \
    --bind='enter:execute(eza_icon_strip {})' \
    "
fi

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
# add-zsh-hook chpwd chpwd_recent_dirs

# Enable Exact-match by fzf-insert-history
typeset -gA FZF_WIDGET_OPTS
FZF_WIDGET_OPTS['insert-history']='--exact'
FZF_WIDGET_OPTS['fzf-git-add-files']='--multi --bind ctrl-space:toggle'

# Start fzf in a tmux pane
# FZF_WIDGET_TMUX=1

# Map widgets to key
bindkey '^\' fzf-select-widget
# bindkey '^@.' fzf-edit-dotfiles
# bindkey '^@c' fzf-change-directory
# bindkey '^@n' fzf-change-named-directory
# bindkey '^@f' fzf-edit-files
# bindkey '^kp' fzf-kill-processes
# bindkey '^@s' fzf-exec-ssh
# bindkey '\e[' fzf-change-recent-directory
# bindkey '\e]' fzf-insert-history
# bindkey '\ef' fzf-insert-files
# bindkey '\ed' fzf-insert-directory
# bindkey '^xn' fzf-insert-named-directory

## Git
# bindkey '\egg' fzf-select-git-widget
bindkey '\ega' fzf-git-add-files
bindkey '\egc' fzf-git-change-repository

# GitHub
# bindkey '^@h' fzf-select-github-widget
# bindkey '^@hs' fzf-github-show-issue
# bindkey '^@hc' fzf-github-close-issue

## Docker
# bindkey '^@d' fzf-select-docker-widget
# bindkey '^@dc' fzf-docker-remove-containers
# bindkey '^@di' fzf-docker-remove-images
# bindkey '^@dv' fzf-docker-remove-volumes
